spring.application.name=Insurance_Reminder

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/insurance_reminder_db
spring.datasource.username=postgres
spring.datasource.password=Sujal

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Gmail SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${user:smp595071@gmail.com}
spring.mail.password=${password:Sujal@7420}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true